export const demoProfile = {
  name: "Aarav Blaze",
  age: 27,
  gender: "MALE" as const,
  heightCm: 178,
  currentWeightKg: 82.6,
  splitPreference: "PPL" as const,
};

export const demoGoal = {
  goalType: "MUSCLE_GAIN" as const,
  activityLevel: "HIGH" as const,
  experienceLevel: "INTERMEDIATE" as const,
  targetWeightKg: 85,
  notes: "Build lean size while keeping the waist tight and strength trending up.",
  weeklyWorkoutTarget: 5,
};

export const demoMeasurements = [
  {
    recordedAt: "2026-02-13T09:00:00.000Z",
    weightKg: 80.9,
    chestCm: 103.2,
    waistCm: 84.6,
    hipsCm: 96.1,
    armCm: 37.7,
    thighCm: 58.1,
    calfCm: 37.0,
    bodyFatPct: 15.8,
  },
  {
    recordedAt: "2026-02-20T09:00:00.000Z",
    weightKg: 81.4,
    chestCm: 103.8,
    waistCm: 84.4,
    hipsCm: 96.2,
    armCm: 38.0,
    thighCm: 58.4,
    calfCm: 37.1,
    bodyFatPct: 15.6,
  },
  {
    recordedAt: "2026-02-27T09:00:00.000Z",
    weightKg: 81.8,
    chestCm: 104.2,
    waistCm: 84.1,
    hipsCm: 96.3,
    armCm: 38.4,
    thighCm: 58.9,
    calfCm: 37.3,
    bodyFatPct: 15.3,
  },
  {
    recordedAt: "2026-03-06T09:00:00.000Z",
    weightKg: 82.2,
    chestCm: 104.7,
    waistCm: 83.8,
    hipsCm: 96.7,
    armCm: 38.8,
    thighCm: 59.2,
    calfCm: 37.4,
    bodyFatPct: 15.1,
  },
  {
    recordedAt: "2026-03-13T09:00:00.000Z",
    weightKg: 82.6,
    chestCm: 105.1,
    waistCm: 83.4,
    hipsCm: 97.0,
    armCm: 39.2,
    thighCm: 59.6,
    calfCm: 37.6,
    bodyFatPct: 14.9,
  },
];

export const demoSessionBlueprints = [
  {
    performedAt: "2026-02-19T12:00:00.000Z",
    daySlug: "push-prime",
    durationMin: 68,
    notes: "Great bar speed on the top sets.",
    logs: [
      { exerciseSlug: "incline-bench-press", setsCompleted: 4, repsCompleted: 7, weightKg: 62.5, achievedMaxKg: 67.5 },
      { exerciseSlug: "seated-dumbbell-shoulder-press", setsCompleted: 4, repsCompleted: 9, weightKg: 26 },
      { exerciseSlug: "machine-chest-fly", setsCompleted: 3, repsCompleted: 12, weightKg: 47.5 },
      { exerciseSlug: "cable-lateral-raise", setsCompleted: 3, repsCompleted: 14, weightKg: 8.5 },
      { exerciseSlug: "rope-pushdown", setsCompleted: 3, repsCompleted: 12, weightKg: 32.5 },
    ],
  },
  {
    performedAt: "2026-02-22T12:00:00.000Z",
    daySlug: "pull-power",
    durationMin: 71,
    notes: "Lats lit up, keep pull-up reps cleaner.",
    logs: [
      { exerciseSlug: "weighted-pull-up", setsCompleted: 4, repsCompleted: 6, weightKg: 12.5 },
      { exerciseSlug: "chest-supported-row", setsCompleted: 4, repsCompleted: 9, weightKg: 55 },
      { exerciseSlug: "neutral-grip-lat-pulldown", setsCompleted: 3, repsCompleted: 11, weightKg: 60 },
      { exerciseSlug: "rear-delt-fly", setsCompleted: 3, repsCompleted: 15, weightKg: 17.5 },
      { exerciseSlug: "ez-bar-curl", setsCompleted: 3, repsCompleted: 10, weightKg: 27.5 },
    ],
  },
  {
    performedAt: "2026-02-25T12:00:00.000Z",
    daySlug: "legs-launch",
    durationMin: 77,
    notes: "Squat depth was solid. RDL grip nearly gave out.",
    logs: [
      { exerciseSlug: "high-bar-back-squat", setsCompleted: 4, repsCompleted: 6, weightKg: 92.5, achievedMaxKg: 97.5 },
      { exerciseSlug: "romanian-deadlift", setsCompleted: 4, repsCompleted: 8, weightKg: 87.5 },
      { exerciseSlug: "leg-press", setsCompleted: 3, repsCompleted: 12, weightKg: 190 },
      { exerciseSlug: "seated-leg-curl", setsCompleted: 3, repsCompleted: 12, weightKg: 50 },
      { exerciseSlug: "standing-calf-raise", setsCompleted: 4, repsCompleted: 15, weightKg: 72.5 },
    ],
  },
  {
    performedAt: "2026-03-02T12:00:00.000Z",
    daySlug: "push-prime",
    durationMin: 69,
    notes: "Added weight on incline and kept reps stable.",
    logs: [
      { exerciseSlug: "incline-bench-press", setsCompleted: 4, repsCompleted: 8, weightKg: 65, achievedMaxKg: 70 },
      { exerciseSlug: "seated-dumbbell-shoulder-press", setsCompleted: 4, repsCompleted: 9, weightKg: 27.5 },
      { exerciseSlug: "machine-chest-fly", setsCompleted: 3, repsCompleted: 12, weightKg: 50 },
      { exerciseSlug: "cable-lateral-raise", setsCompleted: 3, repsCompleted: 15, weightKg: 9 },
      { exerciseSlug: "rope-pushdown", setsCompleted: 3, repsCompleted: 13, weightKg: 35 },
    ],
  },
  {
    performedAt: "2026-03-06T12:00:00.000Z",
    daySlug: "pull-power",
    durationMin: 72,
    notes: "Rows were up. Curls still have room.",
    logs: [
      { exerciseSlug: "weighted-pull-up", setsCompleted: 4, repsCompleted: 7, weightKg: 12.5 },
      { exerciseSlug: "chest-supported-row", setsCompleted: 4, repsCompleted: 10, weightKg: 57.5 },
      { exerciseSlug: "neutral-grip-lat-pulldown", setsCompleted: 3, repsCompleted: 12, weightKg: 62.5 },
      { exerciseSlug: "rear-delt-fly", setsCompleted: 3, repsCompleted: 15, weightKg: 20 },
      { exerciseSlug: "ez-bar-curl", setsCompleted: 3, repsCompleted: 11, weightKg: 30 },
    ],
  },
  {
    performedAt: "2026-03-10T12:00:00.000Z",
    daySlug: "legs-launch",
    durationMin: 78,
    notes: "Best squat session of the cycle.",
    logs: [
      { exerciseSlug: "high-bar-back-squat", setsCompleted: 4, repsCompleted: 7, weightKg: 95, achievedMaxKg: 100 },
      { exerciseSlug: "romanian-deadlift", setsCompleted: 4, repsCompleted: 8, weightKg: 90 },
      { exerciseSlug: "leg-press", setsCompleted: 3, repsCompleted: 12, weightKg: 200 },
      { exerciseSlug: "seated-leg-curl", setsCompleted: 3, repsCompleted: 13, weightKg: 52.5 },
      { exerciseSlug: "standing-calf-raise", setsCompleted: 4, repsCompleted: 15, weightKg: 77.5 },
    ],
  },
];

export const demoWeeklyDigests = [
  {
    weekStart: "2026-02-23T00:00:00.000Z",
    workoutsCompleted: 4,
    workoutTarget: 5,
    totalVolumeKg: 16082,
    averageCaloriesBurned: 501,
    highlight: "Lower body strength held while body-fat estimate dipped.",
    focusForNextWeek: "Turn that fourth session into a fifth without bloating the plan.",
  },
  {
    weekStart: "2026-03-02T00:00:00.000Z",
    workoutsCompleted: 5,
    workoutTarget: 5,
    totalVolumeKg: 17795,
    averageCaloriesBurned: 518,
    highlight: "Incline bench and squat both moved up together.",
    focusForNextWeek: "Drive pulling volume and keep waist under 84cm.",
  },
];
