export type SplitKey = "PPL" | "BRO";

export type WorkoutExerciseTemplate = {
  slug: string;
  name: string;
  muscleGroup:
    | "CHEST"
    | "BACK"
    | "SHOULDERS"
    | "LEGS"
    | "BICEPS"
    | "TRICEPS"
    | "GLUTES"
    | "HAMSTRINGS"
    | "QUADS"
    | "CALVES"
    | "CORE"
    | "FULL_BODY";
  equipment: string;
  instructions: string;
  progressCue: string;
  targetSets: number;
  repRangeMin: number;
  repRangeMax: number;
  restSeconds: number;
};

export type WorkoutDayTemplateShape = {
  slug: string;
  name: string;
  focus: string;
  accent: string;
  description: string;
  estimatedMinutes: number;
  exercises: WorkoutExerciseTemplate[];
};

export const splitOptions = [
  {
    key: "PPL" as const,
    label: "Push Pull Legs",
    description:
      "Balanced hypertrophy flow with built-in recovery and clearer strength progression.",
    vibe: "Performance rhythm",
  },
  {
    key: "BRO" as const,
    label: "Bro Split",
    description:
      "Classic body-part focus with more volume per muscle group and a big pump feel.",
    vibe: "Body-part attack",
  },
];

export const workoutTemplates: Record<SplitKey, WorkoutDayTemplateShape[]> = {
  PPL: [
    {
      slug: "push-prime",
      name: "Push Prime",
      focus: "Chest, shoulders, triceps",
      accent: "#ffd54f",
      description: "Heavy presses first, delts and triceps polished after.",
      estimatedMinutes: 68,
      exercises: [
        {
          slug: "incline-bench-press",
          name: "Incline Bench Press",
          muscleGroup: "CHEST",
          equipment: "Barbell",
          instructions: "Drive through the upper chest and keep the ribcage tall.",
          progressCue: "Add 2.5kg once you own the top of the rep range.",
          targetSets: 4,
          repRangeMin: 6,
          repRangeMax: 8,
          restSeconds: 150,
        },
        {
          slug: "seated-dumbbell-shoulder-press",
          name: "Seated Dumbbell Shoulder Press",
          muscleGroup: "SHOULDERS",
          equipment: "Dumbbells",
          instructions: "Keep wrists stacked and elbows slightly forward.",
          progressCue: "Chase clean lockouts before loading heavier.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 120,
        },
        {
          slug: "machine-chest-fly",
          name: "Machine Chest Fly",
          muscleGroup: "CHEST",
          equipment: "Machine",
          instructions: "Squeeze inward slowly and control the eccentric.",
          progressCue: "Pause for one second in the contracted position.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 75,
        },
        {
          slug: "cable-lateral-raise",
          name: "Cable Lateral Raise",
          muscleGroup: "SHOULDERS",
          equipment: "Cable",
          instructions: "Lead with the elbow and stop just above shoulder height.",
          progressCue: "Own the tempo, then add a rep before weight.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
        {
          slug: "rope-pushdown",
          name: "Rope Pushdown",
          muscleGroup: "TRICEPS",
          equipment: "Cable",
          instructions: "Split the rope hard at the bottom without swinging.",
          progressCue: "Finish the set with elbows pinned, not shoulders rolling.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 14,
          restSeconds: 60,
        },
      ],
    },
    {
      slug: "pull-power",
      name: "Pull Power",
      focus: "Back width, rear delts, biceps",
      accent: "#79d2c0",
      description: "Upper-back density and lat width with smart arm finishers.",
      estimatedMinutes: 72,
      exercises: [
        {
          slug: "weighted-pull-up",
          name: "Weighted Pull-Up",
          muscleGroup: "BACK",
          equipment: "Bodyweight",
          instructions: "Chest up, pull elbows to ribs, avoid leg swing.",
          progressCue: "Add 1.25kg when all sets stay explosive.",
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 8,
          restSeconds: 150,
        },
        {
          slug: "chest-supported-row",
          name: "Chest Supported Row",
          muscleGroup: "BACK",
          equipment: "Machine",
          instructions: "Drive elbows back and pause on the top.",
          progressCue: "Beat last week with one extra rep before load.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 120,
        },
        {
          slug: "neutral-grip-lat-pulldown",
          name: "Neutral Grip Lat Pulldown",
          muscleGroup: "BACK",
          equipment: "Cable",
          instructions: "Pull to upper chest and control the stretch overhead.",
          progressCue: "Think elbows to hips, not hands to chest.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 75,
        },
        {
          slug: "rear-delt-fly",
          name: "Rear Delt Fly",
          muscleGroup: "SHOULDERS",
          equipment: "Machine",
          instructions: "Keep traps quiet and sweep with the upper arm.",
          progressCue: "Use cleaner range before adding plates.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
        {
          slug: "ez-bar-curl",
          name: "EZ Bar Curl",
          muscleGroup: "BICEPS",
          equipment: "Barbell",
          instructions: "Keep elbows under shoulders and resist on the way down.",
          progressCue: "Stay strict and add reps across all working sets.",
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 60,
        },
      ],
    },
    {
      slug: "legs-launch",
      name: "Legs Launch",
      focus: "Quads, glutes, hamstrings, calves",
      accent: "#ff9f68",
      description: "Squat-centered lower-body work with posterior-chain support.",
      estimatedMinutes: 76,
      exercises: [
        {
          slug: "high-bar-back-squat",
          name: "High Bar Back Squat",
          muscleGroup: "QUADS",
          equipment: "Barbell",
          instructions: "Brace hard, sit between the hips, and drive evenly up.",
          progressCue: "When depth and speed stay clean, add 2.5kg.",
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 8,
          restSeconds: 180,
        },
        {
          slug: "romanian-deadlift",
          name: "Romanian Deadlift",
          muscleGroup: "HAMSTRINGS",
          equipment: "Barbell",
          instructions: "Push hips back and keep lats packed all set long.",
          progressCue: "Grow range first, then chase extra load.",
          targetSets: 4,
          repRangeMin: 6,
          repRangeMax: 8,
          restSeconds: 150,
        },
        {
          slug: "leg-press",
          name: "Leg Press",
          muscleGroup: "LEGS",
          equipment: "Machine",
          instructions: "Full depth, knees track with toes, no bouncing.",
          progressCue: "Own 12 reps before stacking another plate.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 90,
        },
        {
          slug: "seated-leg-curl",
          name: "Seated Leg Curl",
          muscleGroup: "HAMSTRINGS",
          equipment: "Machine",
          instructions: "Keep hips pinned and squeeze the shortened position.",
          progressCue: "Pause hard on every rep, then progress load.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 14,
          restSeconds: 75,
        },
        {
          slug: "standing-calf-raise",
          name: "Standing Calf Raise",
          muscleGroup: "CALVES",
          equipment: "Machine",
          instructions: "Stretch long at the bottom and rise with control.",
          progressCue: "Use slower eccentrics before jumping weight.",
          targetSets: 4,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
      ],
    },
  ],
  BRO: [
    {
      slug: "chest-carve",
      name: "Chest Carve",
      focus: "Chest thickness and upper-pec detail",
      accent: "#ffd54f",
      description: "Classic chest day with pressing strength and cable finishers.",
      estimatedMinutes: 70,
      exercises: [
        {
          slug: "flat-bench-press",
          name: "Flat Bench Press",
          muscleGroup: "CHEST",
          equipment: "Barbell",
          instructions: "Plant the feet and keep the bar path deliberate.",
          progressCue: "Add 2.5kg when bar speed is still snappy.",
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 8,
          restSeconds: 150,
        },
        {
          slug: "incline-dumbbell-press",
          name: "Incline Dumbbell Press",
          muscleGroup: "CHEST",
          equipment: "Dumbbells",
          instructions: "Pull shoulder blades down into the bench.",
          progressCue: "Beat last week's total reps before loading heavier.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 120,
        },
        {
          slug: "low-to-high-cable-fly",
          name: "Low To High Cable Fly",
          muscleGroup: "CHEST",
          equipment: "Cable",
          instructions: "Sweep upward and pause without shrugging.",
          progressCue: "Stay smooth and stretch the eccentric.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
        {
          slug: "assisted-dips",
          name: "Assisted Dips",
          muscleGroup: "CHEST",
          equipment: "Machine",
          instructions: "Lean slightly forward and keep elbows controlled.",
          progressCue: "Reduce assistance gradually as control improves.",
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 75,
        },
      ],
    },
    {
      slug: "back-build",
      name: "Back Build",
      focus: "Back density and lat stretch",
      accent: "#79d2c0",
      description: "Heavy posterior-chain pull with rows and pulldowns.",
      estimatedMinutes: 74,
      exercises: [
        {
          slug: "conventional-deadlift",
          name: "Conventional Deadlift",
          muscleGroup: "BACK",
          equipment: "Barbell",
          instructions: "Wedge into the bar and drive the floor away.",
          progressCue: "Move fast singles before loading further.",
          targetSets: 3,
          repRangeMin: 3,
          repRangeMax: 5,
          restSeconds: 180,
        },
        {
          slug: "wide-grip-pulldown",
          name: "Wide Grip Pulldown",
          muscleGroup: "BACK",
          equipment: "Cable",
          instructions: "Pull shoulders down first, then elbows.",
          progressCue: "Keep every rep identical and crisp.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 90,
        },
        {
          slug: "seated-cable-row",
          name: "Seated Cable Row",
          muscleGroup: "BACK",
          equipment: "Cable",
          instructions: "Finish with the elbows and stop torso sway.",
          progressCue: "Pause longer on the final two reps of each set.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 75,
        },
        {
          slug: "straight-arm-pulldown",
          name: "Straight Arm Pulldown",
          muscleGroup: "BACK",
          equipment: "Cable",
          instructions: "Sweep through the lats with soft elbows.",
          progressCue: "Keep abs tight and ribcage stacked.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
      ],
    },
    {
      slug: "shoulder-sculpt",
      name: "Shoulder Sculpt",
      focus: "Delts and upper-frame shape",
      accent: "#8db4ff",
      description: "Strong overhead work followed by high-tension delt volume.",
      estimatedMinutes: 62,
      exercises: [
        {
          slug: "standing-overhead-press",
          name: "Standing Overhead Press",
          muscleGroup: "SHOULDERS",
          equipment: "Barbell",
          instructions: "Brace the trunk and press in a straight line.",
          progressCue: "Add weight only if the lockout stays strong.",
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 8,
          restSeconds: 150,
        },
        {
          slug: "dumbbell-lateral-raise",
          name: "Dumbbell Lateral Raise",
          muscleGroup: "SHOULDERS",
          equipment: "Dumbbells",
          instructions: "Lead with elbows and keep the shrug out.",
          progressCue: "Slow the lowering phase before increasing load.",
          targetSets: 4,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
        {
          slug: "reverse-pec-deck",
          name: "Reverse Pec Deck",
          muscleGroup: "SHOULDERS",
          equipment: "Machine",
          instructions: "Open the arms wide and keep neck relaxed.",
          progressCue: "Try extra pauses before more plates.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
        {
          slug: "cable-y-raise",
          name: "Cable Y Raise",
          muscleGroup: "SHOULDERS",
          equipment: "Cable",
          instructions: "Raise in a Y path and hold the top position.",
          progressCue: "Earn range and control before heavier pins.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 60,
        },
      ],
    },
    {
      slug: "arm-arsenal",
      name: "Arm Arsenal",
      focus: "Biceps and triceps volume",
      accent: "#ff9f68",
      description: "Alternating curls and extensions to keep the pump rolling.",
      estimatedMinutes: 58,
      exercises: [
        {
          slug: "barbell-curl",
          name: "Barbell Curl",
          muscleGroup: "BICEPS",
          equipment: "Barbell",
          instructions: "Stay tall and don't drift the elbows back.",
          progressCue: "Add reps before swinging the bar.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 75,
        },
        {
          slug: "hammer-curl",
          name: "Hammer Curl",
          muscleGroup: "BICEPS",
          equipment: "Dumbbells",
          instructions: "Keep the wrist neutral and elbows pinned.",
          progressCue: "Own both arms evenly before increasing weight.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 60,
        },
        {
          slug: "skull-crusher",
          name: "Skull Crusher",
          muscleGroup: "TRICEPS",
          equipment: "EZ Bar",
          instructions: "Let the bar travel behind the head for stretch.",
          progressCue: "Stay strict and don't flare elbows out.",
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 75,
        },
        {
          slug: "rope-overhead-extension",
          name: "Rope Overhead Extension",
          muscleGroup: "TRICEPS",
          equipment: "Cable",
          instructions: "Keep ribs down and reach long at the bottom.",
          progressCue: "Stretch fully and own the lockout.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
      ],
    },
    {
      slug: "leg-foundry",
      name: "Leg Foundry",
      focus: "Full lower-body hypertrophy",
      accent: "#73d89f",
      description: "Heavy compound work backed by machine volume and calves.",
      estimatedMinutes: 78,
      exercises: [
        {
          slug: "front-squat",
          name: "Front Squat",
          muscleGroup: "QUADS",
          equipment: "Barbell",
          instructions: "Elbows high, torso tall, and knees forward.",
          progressCue: "Add 2.5kg once posture stays upright on every rep.",
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 8,
          restSeconds: 180,
        },
        {
          slug: "hack-squat",
          name: "Hack Squat",
          muscleGroup: "LEGS",
          equipment: "Machine",
          instructions: "Stay controlled through depth and keep feet planted.",
          progressCue: "Beat total reps before loading up.",
          targetSets: 4,
          repRangeMin: 8,
          repRangeMax: 10,
          restSeconds: 120,
        },
        {
          slug: "lying-leg-curl",
          name: "Lying Leg Curl",
          muscleGroup: "HAMSTRINGS",
          equipment: "Machine",
          instructions: "Press hips into the pad for a clean squeeze.",
          progressCue: "Pause the top to make each rep count.",
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 12,
          restSeconds: 75,
        },
        {
          slug: "walking-lunge",
          name: "Walking Lunge",
          muscleGroup: "GLUTES",
          equipment: "Dumbbells",
          instructions: "Long stride, torso tall, and drive off the front foot.",
          progressCue: "Increase total steps before heavier dumbbells.",
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 16,
          restSeconds: 75,
        },
        {
          slug: "seated-calf-raise",
          name: "Seated Calf Raise",
          muscleGroup: "CALVES",
          equipment: "Machine",
          instructions: "Full stretch and a hard squeeze up top.",
          progressCue: "Extend the pause, then chase extra load.",
          targetSets: 4,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
        },
      ],
    },
  ],
};
